// Follow this setup guide to integrate the Deno language server with your editor:
// https://deno.land/manual/getting_started/setup_your_environment
// This enables autocomplete, go to definition, etc.

import { serve } from "https://deno.land/std@0.177.0/http/server.ts"

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req: Request) => {
  // Handle CORS for browser requests (preflight)
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    if (!RESEND_API_KEY) {
      throw new Error("Missing RESEND_API_KEY environment variable. Check Supabase Secrets.");
    }

    const body = await req.json();
    const { vendorEmail, vendorName, items, notes, requestorName } = body;

    if (!vendorEmail || !vendorName || !items || items.length === 0) {
       throw new Error("Missing required payload properties: vendorEmail, vendorName, or items.");
    }

    const htmlBody = `
      <div style="font-family: sans-serif; max-w-xl; color: #333;">
        <h2 style="color: #4F46E5;">Request for Quote</h2>
        <p>Hello <strong>${vendorName}</strong>,</p>
        <p>You have received a new Request for Quote (RFQ) from CommanderOS generated by ${requestorName || 'the procurement team'}. Please review the requested items below and reply to this email with pricing and lead time estimates.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <thead>
            <tr style="background-color: #f3f4f6; text-align: left;">
              <th style="padding: 12px; border: 1px solid #e5e7eb;">Item / SKU</th>
              <th style="padding: 12px; border: 1px solid #e5e7eb;">Quantity</th>
            </tr>
          </thead>
          <tbody>
            ${items.map((item: any) => `
              <tr>
                <td style="padding: 12px; border: 1px solid #e5e7eb;">${item.PRODUCT_NAME || item.PRODUCT_ID} <br/><small style="color: #6b7280;">${item.PRODUCT_ID}</small></td>
                <td style="padding: 12px; border: 1px solid #e5e7eb;">${item.quantityNeeded}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        ${notes ? `
        <div style="margin-top: 20px; padding: 16px; background-color: #fef3c7; border-left: 4px solid #f59e0b;">
          <strong>Additional Notes:</strong><br/>
          ${notes}
        </div>
        ` : ''}

        <p style="margin-top: 30px; font-size: 12px; color: #9ca3af;">System Generated by CommanderOS Procurement Engine.</p>
      </div>
    `;

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`
      },
      body: JSON.stringify({
        // For production, ‘from’ should ideally be a verified domain on Resend (e.g. procurement@yourdomain.com)
        // Since we don't have one configured, Resend's test domain requires sending to the email used to register.
        // If the API key is full-access and domain is verified, this will work natively.
        from: 'CommanderOS Procurement <onboarding@resend.dev>',
        to: vendorEmail,
        subject: `RFQ: New Quote Requested from CommanderOS`,
        html: htmlBody,
      }),
    });

    const data = await res.json();

    if (!res.ok) {
       console.error("Resend API Error:", data);
       throw new Error(data.message || 'Failed to dispatch email via Resend.');
    }

    return new Response(
      JSON.stringify({ success: true, message: `Email successfully delivered to ${vendorEmail}`, resendId: data.id }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      },
    );
  } catch (error: any) {
    console.error("RFQ Edge Function Error:", error.message);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 400,
      },
    );
  }
});
