import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def send_rfq_email(to_email: str, vendor_name: str, requested_by: str, items: list) -> bool:
    """
    Sends an automated Request for Quote (RFQ) email to a specified vendor using SMTP credentials
    defined in environment variables.

    Args:
        to_email: The vendor's email address
        vendor_name: The vendor's name
        requested_by: The user who requested the quote
        items: List of dictionaries representing the products requested

    Returns:
        True if the email was dispatched successfully, False otherwise.
    """
    smtp_host = os.environ.get("SMTP_HOST")
    smtp_port = os.environ.get("SMTP_PORT", 587)
    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASS")
    smtp_from = os.environ.get("SMTP_FROM", "procurement@commanderos.local")

    # If SMTP is not actively configured, fallback gracefully
    if not smtp_host or not smtp_user or not smtp_pass:
        print(f"[WARNING] SMTP credentials not fully configured. Mocking email send to {to_email} ({vendor_name}).")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Request for Quote - CommanderOS"
    msg["From"] = smtp_from
    msg["To"] = to_email

    # Format the items table
    items_html = ""
    items_text = ""
    for item in items:
        name = item.get("PRODUCT_NAME", "Unknown Product")
        qty = item.get("QUANTITY_NEEDED", 0)
        uom = item.get("UNIT_OF_MEASURE", "each")
        items_html += f"<tr><td style='padding:8px;border-bottom:1px solid #ddd;'>{name}</td><td style='padding:8px;border-bottom:1px solid #ddd;text-align:right;'>{qty} {uom}</td></tr>"
        items_text += f"- {name}: {qty} {uom}\n"

    # Text version
    text = f"""
    Hello {vendor_name},

    You have received a new Request for Quote (RFQ) generated by {requested_by}.
    Please provide pricing and estimated lead times for the following items:

    {items_text}

    Please reply directly to this email with your finalized quote.

    Thank you,
    CommanderOS Procurement
    """

    # HTML version
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
            <h2 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">Request for Quote</h2>
            <p>Hello <strong>{vendor_name}</strong>,</p>
            <p>You have received a new Request for Quote (RFQ) generated by <strong>{requested_by}</strong> on {datetime.now().strftime("%B %d, %Y")}.</p>
            <p>Please provide pricing and estimated lead times for the following items:</p>
            
            <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                <thead>
                    <tr style="background-color: #f8fafc;">
                        <th style="padding: 10px; border-bottom: 2px solid #ddd; text-align: left;">Product</th>
                        <th style="padding: 10px; border-bottom: 2px solid #ddd; text-align: right;">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    {items_html}
                </tbody>
            </table>
            
            <p style="margin-top: 20px;">Please reply directly to this email with your finalized quote.</p>
            <br/>
            <p style="color: #64748b; font-size: 0.9em;">
                Thank you,<br/>
                <strong>CommanderOS Procurement</strong>
            </p>
        </div>
      </body>
    </html>
    """

    part1 = MIMEText(text, "plain")
    part2 = MIMEText(html, "html")
    msg.attach(part1)
    msg.attach(part2)

    try:
        # Connect to SMTP server
        server = smtplib.SMTP(smtp_host, int(smtp_port))
        server.ehlo()
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_from, to_email, msg.as_string())
        server.quit()
        print(f"[SUCCESS] RFQ Email dispatched to {to_email}")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to send email to {to_email}: {e}")
        return False
